### ISSUE TITLE
Adding deprecation warning really screws up any existing scripts

### ISSUE THREAD

**Issue by SteveH-US** [mongodb/mongodb-atlas-cli#1135]
**Describe the bug**
A clear and concise description of the bug.
The new version of the `mongocli`, v1.24.1 adds the following message
"⚠ There's a new, dedicated Atlas CLI available for Atlas users. Install the Atlas CLI to enjoy the same capabilities and keep getting new features: https://dochub.mongodb.org/core/migrate-to-atlas-cli. Atlas commands for MongoCLI are now deprecated, but you can keep using them for 12 months (until April 30, 2023)."

That really screws up any reports that use this CLI today. There is a less invasive way to tell us than to print out this warning to stderr, which is its an odd way to use stderr. 

**To Reproduce**
1. Run '...'
2. See error

**Expected behavior**
Please explain what you expected to happen.

Please remove this output.

**Screenshots**
If possible, add screenshots to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. Ubuntu Linux 18.04]
 - MongoCLI version [e.g. 1.2]
 - Ops Manager Version: [if applicable]

**Additional context**

**Comment by SteveH-US** [comment]
I think it's sufficient to list that the command is deprecated in the help and not send noise to standard error.

**Comment by SteveH-US** [comment]
bump

**Comment by boooczek** [comment]
@SteveH-US I'm sorry for the late response here and thank you for your previous answer. I'm also very sorry this change had such impact on your work. 
We believe that displaying the message in help will not provide enough visibility to users.
Because of that we've decided to surface it as `stderr`. In order to avoid this change breaking your reports, we recommend piping the `stderr` to a different file. 

In meantime, what're your plans of migrating to the Atlas CLI?

**Comment by SteveH-US** [comment]
I have already migrated to the `atlas` CLI. I had to quickly because of this problem.
