### ISSUE TITLE
atlas quickstart requires projectId

### ISSUE THREAD

**Issue by tom-fitz** [mongodb/mongodb-atlas-cli#1642]
When trying to quickstart a project in with the command `atlas quickstart` it asks for a projectId and acts as though it is a required parameter, when it states in the docs that projectId is not required.

**To Reproduce**
1. Install atlas CLI version 1.4.0
2. Run `atlas quickstart`
3. Command will not complete without a valid projectId

**Expected behavior**
When I run atlas quickstart I expect an atlas project to be spun up with all the defaults filled in.

**Desktop (please complete the following information):**
 - OS: Ubuntu Linux 20.04.5LTS
 - MongoCLI version 3.6.8

**Additional context**
There are a few work arounds. One is using the atlas UI, and the other is running `atlas setup`

**Comment by gssbzn** [comment]
Hi @tom-fitz, from 
```bash
atlas quickstart --help
```

> --projectId string       Project ID to use. Overrides the settings in the configuration file or environment variable.

Right now it's marking it as mandatory because it's not able to detect it from your configuration file or an env variable

My guess would be a misconfiguration or a previous attempt to use quickstart may have left your config in incorrect state.

Can you verify the content of your configuration via `atlas config edit`? 

Depending on the type of authentication you are using, API keys vs `atlas auth login` you may need to include your project id to the config file or use the flag

You can also try with a new profile like

```bash
atlas quickstart -P quickstart
```

Which should start from scratch without risk of loosing the credentials you may be using currently

**Comment by tom-fitz** [comment]
@gssbzn Not sure what you want me to verify about the config, but here is the output below. I obviously didn't copy over the keys, but you get the idea.
```
[default]
access_token = 'access--token'
refresh_token = 'refresh--token'
service = 'cloud'
```

> Depending on the type of authentication you are using, API keys vs atlas auth login you may need to include your project id to the config file or use the flag

Why would a projectId ever be required when trying to `quickstart` a project? And If so, your documentation should reflect that.

**Comment by gssbzn** [comment]
>Not sure what you want me to verify about the config

That you are indeed missing a project ID

> Why would a projectId ever be required when trying to quickstart a project? 

from `atlas quickstart --help`
> This command creates a new cluster, adds your public IP to the Atlas access list, creates a database user to access your new MongoDB instance, loads sample data, and connects to the new cluster using Mongosh.

All those operations are bound to a project, ideally when you log in you'll be asked for a project ID, for example, when running `quickstart` the first time it'll try to log in and set up a profile

```bash
atlas quickstart --profile test
This action requires authentication.

To verify your account, copy your one-time verification code:
XXXX-XXXX

Paste the code in the browser when prompted to activate your Atlas CLI. Your code will expire after 10 minutes.

To continue, go to https://account.mongodb.com/account/connect
Successfully logged in as test@test.com.
Now set your default organization and project.

You have multiple organizations or projects, select one to proceed.
? Choose a default project:  [Use arrows to move, type to filter]
> 622791184eb015458d4f864d - Test
```
A default project ID can be skipped as some users prefer to use flags some users prefer to use env variables

In your case, as showed by your config you lack a project ID so we need more information if this was intentional or if you have any additional details on how your login experience was, right now by the usage of an access token I assume you ran `atlas auth login` instead of `atlas config init`.

> your documentation should reflect that and describe when and why it's required

Here's the source for the documentation of the `projectId` flag https://github.com/mongodb/mongodb-atlas-cli/blob/0ae68e3e40fa1358f5f2db7beaf778525c6ea11c/internal/flag/flags.go#L25 we welcome contributions to improve it
